# Generated by Django 5.1.3 on 2024-11-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
    ]
