# Generated by Django 5.1.3 on 2024-11-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('K', 'Kadın'), ('E', 'Erkek')], max_length=10, null=True),
        ),
    ]
