# Generated by Django 5.1.3 on 2024-11-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_event_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Onay Bekleniyor'), ('approved', 'Kabul Edildi'), ('rejected', 'Reddedildi')], default='pending', max_length=20),
        ),
    ]
