# Generated by Django 5.1.3 on 2024-11-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_event_is_approved_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylanmış'), ('rejected', 'Reddedilmiş')], default='pending', max_length=10),
        ),
    ]
