# Generated by Django 5.1.3 on 2024-11-29 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='join_date',
            new_name='joined_at',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='date_earned',
            new_name='date_awarded',
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='participants', through='users.Participant', to='users.event'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='points',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
