# Generated by Django 5.1.3 on 2024-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_join_date_participant_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='point_type',
            field=models.CharField(choices=[('join_event', 'Etkinliğe Katılım'), ('create_event', 'Etkinlik Oluşturma'), ('first_join_bonus', 'İlk Katılım Bonusu')], default='join_event', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.points'),
        ),
    ]
