# Generated by Django 5.1.3 on 2024-11-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_points_point_type_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='participants', through='users.Participant', to='users.event'),
        ),
    ]
