# Generated by Django 5.1.3 on 2024-11-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_points_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.points'),
        ),
    ]
